name: Daily Mercari scrape

permissions:
  contents: write          # ← push 権限

on:
  schedule:
    - cron: "0 21 * * *"   # JST 06:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run scraper
        run: python scrape.py

      - name: Commit & push if CSV updated
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add latest.csv
            git commit -m "data: $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes"
          fi
